/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as OrientacoesIndexRouteImport } from './routes/orientacoes.index'
import { Route as OrientacoesSlugRouteImport } from './routes/orientacoes.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const OrientacoesIndexRoute = OrientacoesIndexRouteImport.update({
  id: '/orientacoes/',
  path: '/orientacoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrientacoesSlugRoute = OrientacoesSlugRouteImport.update({
  id: '/orientacoes/$slug',
  path: '/orientacoes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/orientacoes/$slug': typeof OrientacoesSlugRoute
  '/orientacoes/': typeof OrientacoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/orientacoes/$slug': typeof OrientacoesSlugRoute
  '/orientacoes': typeof OrientacoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/orientacoes/$slug': typeof OrientacoesSlugRoute
  '/orientacoes/': typeof OrientacoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/politica-de-privacidade'
    | '/servicos'
    | '/sobre'
    | '/orientacoes/$slug'
    | '/orientacoes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/politica-de-privacidade'
    | '/servicos'
    | '/sobre'
    | '/orientacoes/$slug'
    | '/orientacoes'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/politica-de-privacidade'
    | '/servicos'
    | '/sobre'
    | '/orientacoes/$slug'
    | '/orientacoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  ServicosRoute: typeof ServicosRoute
  SobreRoute: typeof SobreRoute
  OrientacoesSlugRoute: typeof OrientacoesSlugRoute
  OrientacoesIndexRoute: typeof OrientacoesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orientacoes/': {
      id: '/orientacoes/'
      path: '/orientacoes'
      fullPath: '/orientacoes/'
      preLoaderRoute: typeof OrientacoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orientacoes/$slug': {
      id: '/orientacoes/$slug'
      path: '/orientacoes/$slug'
      fullPath: '/orientacoes/$slug'
      preLoaderRoute: typeof OrientacoesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  ServicosRoute: ServicosRoute,
  SobreRoute: SobreRoute,
  OrientacoesSlugRoute: OrientacoesSlugRoute,
  OrientacoesIndexRoute: OrientacoesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
